global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/pd.rules.yml'
  - '/etc/prometheus/tikv.rules.yml'
  - '/etc/prometheus/tidb.rules.yml'

scrape_configs:
  - job_name: 'pd'
    honor_labels: true
    static_configs:
      - targets: ['pd0:2379']
        labels:
          instance: 'pd0'

  - job_name: 'tikv'
    honor_labels: true
    static_configs:
      - targets: ['tikv0:20180']
        labels:
          instance: 'tikv0'

  - job_name: 'tidb'
    honor_labels: true
    static_configs:
      - targets: ['tidb:10080']
        labels:
          instance: 'tidb'