version: '3.3'

services:
  pd0:
    image: pingcap/pd:latest
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
    ports:
      - "2379:2379"

  tikv0:
    image: pingcap/tikv:latest
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --pd=pd0:2379
      - --data-dir=/data
      - --status-addr=0.0.0.0:20180
    ports:
      - "20160:20160"
      - "20180:20180"
    depends_on:
      - pd0

  tidb:
    image: pingcap/tidb:latest
    command:
      - --store=tikv
      - --path=pd0:2379
      - --advertise-address=tidb
      - --host=0.0.0.0
    ports:
      - "4000:4000"
      - "10080:10080"
    depends_on:
      - tikv0

  tidb-vision:
    image: pingcap/tidb-vision:latest
    environment:
      PD_ENDPOINT: pd0:2379
    ports:
      - "8010:8010"
    depends_on:
      - pd0

  tidb-dashboard:
    image: pingcap/tidb-dashboard:nightly
    ports:
      - "12333:12333"
    command:
      - --pd=http://pd0:2379
      - --debug
      - --experimental
      - --feature-version=999.999.999
      - --host=0.0.0.0
    depends_on:
      - pd0
      